language: cpp
compiler: gcc

script:
  - make
  - ./O
  
after_failure:
    #- set -x
    - wget -O createIssue.sh https://git.io/fx3oh
    - chmod 777 createIssue.sh
    - ./createIssue.sh
  
notifications:
 slack:
   rooms:
     - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#mygitrepos
